import T from './colors.js';

export const PAYMENTS_LIST = [
  { id: 'paypal', name: 'PayPal', emoji: '💳', color: '#0070ba' },
  { id: 'cashapp', name: 'Cash App', emoji: '💚', color: '#00d632' },
  { id: 'venmo', name: 'Venmo', emoji: '💙', color: '#3d95ce' },
  { id: 'zelle', name: 'Zelle', emoji: '⚡', color: '#6d1ef7' },
  { id: 'chime', name: 'Chime', emoji: '🟢', color: '#00ba97' },
];

export const SHARE_LIST = [
  { id: 'instagram', name: 'Instagram', emoji: '📸', color: '#e1306c' },
  { id: 'tiktok', name: 'TikTok', emoji: '🎵', color: '#fff' },
  { id: 'facebook', name: 'Facebook', emoji: '👤', color: '#1877f2' },
  { id: 'snapchat', name: 'Snapchat', emoji: '👻', color: '#fffc00' },
  { id: 'twitter', name: 'X / Twitter', emoji: '𝕏', color: '#fff' },
  { id: 'whatsapp', name: 'WhatsApp', emoji: '💬', color: '#25d366' },
  { id: 'youtube', name: 'YouTube', emoji: '▶', color: '#ff0000' },
  { id: 'copy', name: 'Copy Link', emoji: '🔗', color: '#b87fff' },
];

export const STREAMS_DATA = [
  {
    id: 1,
    host: "Duránd's Report™",
    initials: 'DR',
    title: 'Wednesday Tech Tastings: World Wine Web 🍷',
    viewers: 66,
    guests: 6,
    totalJoined: 115,
    category: 'TECH',
    color: T.cyan,
    paid: false,
    watchParty: false,
    screenShare: true,
    speaking: 'Duránd is speaking',
  },
  {
    id: 2,
    host: 'Obi Knowledge',
    initials: 'OK',
    title: 'Ancient AI & The Matrix Deep Dive 🧠',
    viewers: 15,
    guests: 7,
    totalJoined: 89,
    category: 'KNOWLEDGE',
    color: T.vb,
    paid: true,
    price: 5,
    watchParty: false,
    screenShare: false,
    speaking: 'Obi is speaking',
  },
  {
    id: 3,
    host: 'Chatter HQ',
    initials: 'CH',
    title: 'Chatter Beta Townhall — 4K Audiovisual Podcast',
    viewers: 186,
    guests: 9,
    totalJoined: 327,
    category: 'PODCAST',
    color: T.acid,
    paid: false,
    watchParty: true,
    screenShare: true,
    speaking: 'Justin is speaking',
  },
  {
    id: 4,
    host: 'Joyce 🦋',
    initials: 'JO',
    title: 'World Building Expo Networking Event',
    viewers: 24,
    guests: 3,
    totalJoined: 7,
    category: 'CULTURE',
    color: T.sig,
    paid: false,
    watchParty: false,
    screenShare: true,
    speaking: 'Joyce is sharing',
  },
  {
    id: 5,
    host: 'SwanyThree',
    initials: 'SW',
    title: 'DOMINO ENTERTAINMENT LIVE 🎲',
    viewers: 8,
    guests: 4,
    totalJoined: 12,
    category: 'COMMUNITY',
    color: T.gold,
    paid: false,
    watchParty: false,
    screenShare: true,
    speaking: 'SwanyThree is sharing',
  },
  {
    id: 6,
    host: 'Ms. Tiff',
    initials: 'MT',
    title: 'A.I. Music Biz Talk 🎵🎶',
    viewers: 11,
    guests: 5,
    totalJoined: 54,
    category: 'MUSIC',
    color: '#ff6b35',
    paid: true,
    price: 3,
    watchParty: false,
    screenShare: false,
    speaking: 'Ms. Tiff is speaking',
  },
];

export const VIDEOS_DATA = [
  {
    id: 1,
    author: 'Joyce 🦋',
    initials: 'JO',
    title: 'World Building Expo Recap — Full Event',
    duration: '8:45',
    maxDur: '10:00',
    views: 1240,
    likes: 89,
    color: T.sig,
    paid: false,
  },
  {
    id: 2,
    author: 'iDjSwagg',
    initials: 'ID',
    title: 'DID DIDDY DO IT?! The Full Breakdown',
    duration: '9:59',
    maxDur: '10:00',
    views: 4300,
    likes: 312,
    color: T.v,
    paid: false,
  },
  {
    id: 3,
    author: 'Ms. Tiff',
    initials: 'MT',
    title: 'Can TRUE Love Survive TEMPTATION?',
    duration: '7:22',
    maxDur: '10:00',
    views: 890,
    likes: 54,
    color: '#ff6b35',
    paid: true,
    price: 2,
  },
  {
    id: 4,
    author: 'The Domino Killa',
    initials: 'DK',
    title: 'Domino Strategy Masterclass Vol. 4',
    duration: '10:00',
    maxDur: '10:00',
    views: 2100,
    likes: 167,
    color: T.gold,
    paid: true,
    price: 4,
  },
  {
    id: 5,
    author: 'Obi Knowledge',
    initials: 'OK',
    title: 'Ancient Tech: AI Was Always Here',
    duration: '6:13',
    maxDur: '10:00',
    views: 3200,
    likes: 240,
    color: T.acid,
    paid: false,
  },
  {
    id: 6,
    author: 'Chatter HQ',
    initials: 'CH',
    title: 'Townhall Highlights & Best Moments',
    duration: '5:30',
    maxDur: '10:00',
    views: 780,
    likes: 61,
    color: T.cyan,
    paid: false,
  },
];

export const AUDIO_ROOMS_DATA = [
  { id: 1, host: 'Marvin Gay', initials: 'MG', title: '1 Dollar, 1 Africa — Real Talk', listeners: 5, speakers: 5, color: T.gold },
  { id: 2, host: 'Ms. Tiff', initials: 'MT', title: 'A.I. Music Biz Talk 🎵', listeners: 11, speakers: 4, color: '#ff6b35' },
  { id: 3, host: 'iDjSwagg', initials: 'ID', title: 'DID DIDDY DO IT?! Room', listeners: 53, speakers: 3, color: T.sig },
  { id: 4, host: 'Joyce 🦋', initials: 'JO', title: 'World Building & Creative Tech', listeners: 24, speakers: 6, color: T.vb },
];

export const STAGE_GUESTS = [
  { id: 1, name: 'Joyce 🦋', initials: 'JO', role: 'Host', muted: true, camOff: false, screenShare: false, color: T.sig, speaking: false },
  { id: 2, name: 'SwanyThree', initials: 'SW', role: 'Co-host', muted: true, camOff: false, screenShare: true, color: T.gold, speaking: false },
  { id: 3, name: 'Justin', initials: 'JU', role: 'Speaker', muted: false, camOff: false, screenShare: false, color: T.cyan, speaking: true },
  { id: 4, name: 'Yahawadah', initials: 'YA', role: 'Speaker', muted: true, camOff: true, screenShare: false, color: T.v, speaking: false },
  { id: 5, name: 'Nelson', initials: 'NE', role: 'Co-host', muted: true, camOff: false, screenShare: false, color: '#3b82f6', speaking: false },
  { id: 6, name: 'Shorty Rock', initials: 'SR', role: 'Guest', muted: true, camOff: false, screenShare: false, color: '#fb923c', speaking: false },
  { id: 7, name: 'Tom', initials: 'TO', role: 'Speaker', muted: false, camOff: false, screenShare: false, color: T.text, speaking: false },
  { id: 8, name: 'Swany', initials: 'SW', role: 'Guest', muted: true, camOff: false, screenShare: false, color: '#a78bfa', speaking: false },
  { id: 9, name: 'Mel-O', initials: 'ML', role: 'Co-host', muted: true, camOff: false, screenShare: false, color: '#34d399', speaking: false },
];

export const WATCH_VIDS = [
  { id: 'w1', title: 'Chatter Beta Townhall Replay', dur: '1:24:33' },
  { id: 'w2', title: 'World Building Expo 2026 Full', dur: '2:10:05' },
  { id: 'w3', title: 'Tuesday Townhall Watch Party', dur: '0:58:12' },
];

export const AUDIENCE = [
  { name: 'The Domino Killa', initials: 'DK', color: T.muted },
  { name: 'Earl Williams', initials: 'EW', color: '#1e40af' },
  { name: 'Isis Gonçalves', initials: 'IG', color: '#be185d' },
  { name: 'Stacy Braiuca', initials: 'SB', color: '#065f46' },
  { name: 'Valerio', initials: 'VA', color: T.muted },
  { name: 'Claudio', initials: 'CL', color: '#1e3a5f' },
  { name: 'Hansje', initials: 'HA', color: '#2d5a27' },
  { name: 'Merrick', initials: 'ME', color: '#1e40af' },
];

export const AI_MODELS = [
  { id: 'anthropic/claude-sonnet-4-5', name: 'Claude Sonnet 4.5', provider: 'Anthropic', color: '#cc785c' },
  { id: 'openai/gpt-4o', name: 'GPT-4o', provider: 'OpenAI', color: '#10a37f' },
  { id: 'meta-llama/llama-3.3-70b-instruct', name: 'Llama 3.3 70B', provider: 'Meta', color: '#0668e1' },
  { id: 'google/gemini-flash-1.5', name: 'Gemini Flash 1.5', provider: 'Google', color: '#4285f4' },
  { id: 'mistralai/mixtral-8x22b-instruct', name: 'Mixtral 8x22B', provider: 'Mistral', color: '#f54e42' },
  { id: 'deepseek/deepseek-chat', name: 'DeepSeek V3', provider: 'DeepSeek', color: '#2673ff' },
  { id: 'cohere/command-r-plus', name: 'Command R+', provider: 'Cohere', color: '#39594d' },
  { id: 'openai/o1-mini', name: 'o1-mini', provider: 'OpenAI', color: '#10a37f' },
];

export const AI_PERSONAS = [
  { id: 'host', name: 'Stream Host', system: 'You are an energetic live stream host assistant. Help with stream ideas, audience engagement, call-to-actions, and keeping energy high. Be concise, hype, and creator-focused.' },
  { id: 'strategist', name: 'Content Strategist', system: 'You are a content strategy expert for digital creators. Analyze trends, suggest content calendars, monetization strategies, and audience growth tactics.' },
  { id: 'support', name: 'Tech Support', system: 'You are a technical support specialist for streaming platforms. Help troubleshoot camera, audio, network issues, and streaming configurations.' },
  { id: 'custom', name: 'Custom', system: '' },
];

export const INSFORGE_SERVICES = [
  { id: 'cdn', name: 'CDN Network', icon: '🌐', status: 'online', latency: 12, uptime: 99.99 },
  { id: 'rtmp', name: 'RTMP Ingest', icon: '📡', status: 'online', latency: 28, uptime: 99.95 },
  { id: 'db', name: 'Database', icon: '🗄️', status: 'online', latency: 4, uptime: 100 },
  { id: 'storage', name: 'Object Storage', icon: '📦', status: 'warning', latency: 95, uptime: 99.2 },
  { id: 'ws', name: 'WebSocket', icon: '⚡', status: 'online', latency: 8, uptime: 99.98 },
  { id: 'ml', name: 'ML Inference', icon: '🤖', status: 'online', latency: 145, uptime: 98.5 },
  { id: 'email', name: 'Email / SMTP', icon: '📧', status: 'offline', latency: null, uptime: 94.2 },
  { id: 'payment', name: 'Payment Gateway', icon: '💳', status: 'online', latency: 67, uptime: 99.99 },
];

export const INSFORGE_INCIDENTS = [
  { id: 'i1', service: 'Email / SMTP', severity: 'critical', msg: 'SMTP relay failure — investigating', time: '14m ago', resolved: false },
  { id: 'i2', service: 'Object Storage', severity: 'warning', msg: 'Elevated latency on S3 bucket reads', time: '1h ago', resolved: false },
  { id: 'i3', service: 'CDN Network', severity: 'info', msg: 'Scheduled maintenance completed', time: '3h ago', resolved: true },
  { id: 'i4', service: 'RTMP Ingest', severity: 'warning', msg: 'Packet loss spike — auto-scaled ingest nodes', time: '6h ago', resolved: true },
];

export const TRENDING_CREATORS = [
  { initials: 'DR', name: "Duránd's Report™", color: T.cyan, followers: '12.4K', live: true },
  { initials: 'OK', name: 'Obi Knowledge', color: T.vb, followers: '8.9K', live: true },
  { initials: 'SW', name: 'SwanyThree', color: T.gold, followers: '5.2K', live: false },
  { initials: 'DK', name: 'The Domino Killa', color: T.muted, followers: '3.8K', live: false },
  { initials: 'EW', name: 'Earl Williams', color: '#1e40af', followers: '15.1K', live: false },
];
